name: Update README

on:
    workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:   
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      - name: Run script and update README
        id: run-script
        run: |
          OUTPUT=$(python analyze.py)
          echo "::set-output name=script_output::$OUTPUT"
          
      - name: Update README with script output
        run: |
          OUTPUT="${{ steps.run-script.outputs.script_output }}"
          OUTPUT=$(echo $OUTPUT | tr -d '(),' ) # remove brackets and comma
          VALID=$(echo "$OUTPUT" | awk '{print $1}')
          NOT_VALID=$(echo "$OUTPUT" | awk '{print $2}')
          BADGE_URL="https://img.shields.io/badge/Valid-$VALID%25-green"
          BADGE_URL+=" https://img.shields.io/badge/Invalid-$NOT_VALID%25-red"
          sed -i '/last-commit/,/^$/c\![]('"$BADGE_URL"')' README.md

      - name: Commit changes
        if: success()
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Update README statistcs"
    
      - name: Push changes
        if: success()
        run: git push origin HEAD:main