name: Update README

on:
    workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:   
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      - name: Run script and update README
        id: run-script
        run: |
          python analyze.py

      - name: Commit changes
        if: success()
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Update README statistcs badges"
    
      - name: Push changes
        if: success()
        run: git push origin HEAD:main